### ISSUE TITLE
Cassandra data loss

### ISSUE THREAD

**Issue by yeudit** [JeremyOT/cassandra-container#2]
I ran two docker containers of jeremyot/cassandra on tow different machines with same etcd:
1. docker run --rm --net=host --add-host=`hostname`:$(ifconfig eth0 | grep 'inet ' | awk '{ print $2}') --name cassandra -v /var/cassandra/data:/var/cassandra/data -p 9042:9042 -p 9160:9160 jeremyot/cassandra autoscale "$(ifconfig docker0 | grep 'inet ' | awk '{ print $2}'):4001" service/Cassandra --authenticator=PasswordAuthenticator --authorizer=CassandraAuthorizer
2. docker run --rm --net=host --add-host=`hostname`:$(ifconfig eth0 | grep 'inet ' | awk '{ print $2}') --name cassandra -v /var/cassandra/data:/var/cassandra/data -p 9042:9042 -p 9160:9160 jeremyot/cassandra autoscale "$(ifconfig docker0 | grep 'inet ' | awk '{ print $2}'):4001" service/Cassandra --join --authenticator=PasswordAuthenticator --authorizer=CassandraAuthorizer

everything works ok, but when I restart the docker, It seems that the data is lost
I looked at the file system, and I see that the column family folder is empty - the data was not saved there:

ls /var/cassandra/data/keyspace/columnFamily-faf64ce0a70811e4b1a533c3e757b22a/
 => return empty result

but in my local cassandra(without docker), with same db schema, this folder contains some files like:

ls /var/lib/cassandra/data/keyspace/columnFamily
 => keyspace-columnFamily-jb-1-CompressionInfo.db                          keyspace-columnFamily.columnFamily_name_idx-jb-1-Statistics.db
keyspace-columnFamily-jb-1-Data.db                                     keyspace-columnFamily.columnFamily_name_idx-jb-1-Summary.db
.........................
.........................

any idea? something I didn't configure?

Thanks!

Yehudit

**Comment by yeudit** [comment]
found the problem!
I just had to mount a volume with -v for these folders :
"/var/cassandra/commitlog", "/var/cassandra/saved_caches", "/var/cassandra/data", "/var/cassandra/config", "/var/logs/cassandra"

**Comment by JeremyOT** [comment]
Ah that makes sense, Cassandra's data is split between /data and /commitlog - it's only flushed to /data when certain thresholds are met. You may just want to mount with `-v /var/cassandra -v /var/logs/cassandra`
